// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qa.domain;

import com.foamtec.qa.domain.EngSendItem;
import com.foamtec.qa.domain.EngSendItemDataOnDemand;
import com.foamtec.qa.domain.EngSendItemIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EngSendItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EngSendItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EngSendItemIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EngSendItemIntegrationTest: @Transactional;
    
    @Autowired
    EngSendItemDataOnDemand EngSendItemIntegrationTest.dod;
    
    @Test
    public void EngSendItemIntegrationTest.testCountEngSendItems() {
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", dod.getRandomEngSendItem());
        long count = EngSendItem.countEngSendItems();
        Assert.assertTrue("Counter for 'EngSendItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EngSendItemIntegrationTest.testFindEngSendItem() {
        EngSendItem obj = dod.getRandomEngSendItem();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to provide an identifier", id);
        obj = EngSendItem.findEngSendItem(id);
        Assert.assertNotNull("Find method for 'EngSendItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EngSendItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EngSendItemIntegrationTest.testFindAllEngSendItems() {
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", dod.getRandomEngSendItem());
        long count = EngSendItem.countEngSendItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'EngSendItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EngSendItem> result = EngSendItem.findAllEngSendItems();
        Assert.assertNotNull("Find all method for 'EngSendItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EngSendItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EngSendItemIntegrationTest.testFindEngSendItemEntries() {
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", dod.getRandomEngSendItem());
        long count = EngSendItem.countEngSendItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EngSendItem> result = EngSendItem.findEngSendItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EngSendItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EngSendItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EngSendItemIntegrationTest.testFlush() {
        EngSendItem obj = dod.getRandomEngSendItem();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to provide an identifier", id);
        obj = EngSendItem.findEngSendItem(id);
        Assert.assertNotNull("Find method for 'EngSendItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEngSendItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EngSendItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EngSendItemIntegrationTest.testMergeUpdate() {
        EngSendItem obj = dod.getRandomEngSendItem();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to provide an identifier", id);
        obj = EngSendItem.findEngSendItem(id);
        boolean modified =  dod.modifyEngSendItem(obj);
        Integer currentVersion = obj.getVersion();
        EngSendItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EngSendItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EngSendItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", dod.getRandomEngSendItem());
        EngSendItem obj = dod.getNewTransientEngSendItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EngSendItem' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EngSendItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EngSendItemIntegrationTest.testRemove() {
        EngSendItem obj = dod.getRandomEngSendItem();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EngSendItem' failed to provide an identifier", id);
        obj = EngSendItem.findEngSendItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EngSendItem' with identifier '" + id + "'", EngSendItem.findEngSendItem(id));
    }
    
}
