// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qa.domain;

import com.foamtec.qa.domain.FaRequest;
import com.foamtec.qa.domain.FaRequestDataOnDemand;
import com.foamtec.qa.domain.FaRequestIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FaRequestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FaRequestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FaRequestIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FaRequestIntegrationTest: @Transactional;
    
    @Autowired
    FaRequestDataOnDemand FaRequestIntegrationTest.dod;
    
    @Test
    public void FaRequestIntegrationTest.testCountFaRequests() {
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", dod.getRandomFaRequest());
        long count = FaRequest.countFaRequests();
        Assert.assertTrue("Counter for 'FaRequest' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FaRequestIntegrationTest.testFindFaRequest() {
        FaRequest obj = dod.getRandomFaRequest();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to provide an identifier", id);
        obj = FaRequest.findFaRequest(id);
        Assert.assertNotNull("Find method for 'FaRequest' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FaRequest' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FaRequestIntegrationTest.testFindAllFaRequests() {
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", dod.getRandomFaRequest());
        long count = FaRequest.countFaRequests();
        Assert.assertTrue("Too expensive to perform a find all test for 'FaRequest', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FaRequest> result = FaRequest.findAllFaRequests();
        Assert.assertNotNull("Find all method for 'FaRequest' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FaRequest' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FaRequestIntegrationTest.testFindFaRequestEntries() {
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", dod.getRandomFaRequest());
        long count = FaRequest.countFaRequests();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FaRequest> result = FaRequest.findFaRequestEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FaRequest' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FaRequest' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FaRequestIntegrationTest.testFlush() {
        FaRequest obj = dod.getRandomFaRequest();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to provide an identifier", id);
        obj = FaRequest.findFaRequest(id);
        Assert.assertNotNull("Find method for 'FaRequest' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFaRequest(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FaRequest' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FaRequestIntegrationTest.testMergeUpdate() {
        FaRequest obj = dod.getRandomFaRequest();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to provide an identifier", id);
        obj = FaRequest.findFaRequest(id);
        boolean modified =  dod.modifyFaRequest(obj);
        Integer currentVersion = obj.getVersion();
        FaRequest merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FaRequest' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FaRequestIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", dod.getRandomFaRequest());
        FaRequest obj = dod.getNewTransientFaRequest(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FaRequest' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FaRequest' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FaRequestIntegrationTest.testRemove() {
        FaRequest obj = dod.getRandomFaRequest();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FaRequest' failed to provide an identifier", id);
        obj = FaRequest.findFaRequest(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FaRequest' with identifier '" + id + "'", FaRequest.findFaRequest(id));
    }
    
}
