// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qa.domain;

import com.foamtec.qa.domain.FaRequestDataOnDemand;
import com.foamtec.qa.domain.Material;
import com.foamtec.qa.domain.MaterialDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MaterialDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MaterialDataOnDemand: @Component;
    
    private Random MaterialDataOnDemand.rnd = new SecureRandom();
    
    private List<Material> MaterialDataOnDemand.data;
    
    @Autowired
    FaRequestDataOnDemand MaterialDataOnDemand.faRequestDataOnDemand;
    
    public Material MaterialDataOnDemand.getNewTransientMaterial(int index) {
        Material obj = new Material();
        setBatchNumber(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void MaterialDataOnDemand.setBatchNumber(Material obj, int index) {
        String batchNumber = "batchNumber_" + index;
        obj.setBatchNumber(batchNumber);
    }
    
    public void MaterialDataOnDemand.setName(Material obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Material MaterialDataOnDemand.getSpecificMaterial(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Material obj = data.get(index);
        Long id = obj.getId();
        return Material.findMaterial(id);
    }
    
    public Material MaterialDataOnDemand.getRandomMaterial() {
        init();
        Material obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Material.findMaterial(id);
    }
    
    public boolean MaterialDataOnDemand.modifyMaterial(Material obj) {
        return false;
    }
    
    public void MaterialDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Material.findMaterialEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Material' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Material>();
        for (int i = 0; i < 10; i++) {
            Material obj = getNewTransientMaterial(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
