// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qa.domain;

import com.foamtec.qa.domain.Tooling;
import com.foamtec.qa.domain.ToolingDataOnDemand;
import com.foamtec.qa.domain.ToolingIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ToolingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ToolingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ToolingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ToolingIntegrationTest: @Transactional;
    
    @Autowired
    ToolingDataOnDemand ToolingIntegrationTest.dod;
    
    @Test
    public void ToolingIntegrationTest.testCountToolings() {
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", dod.getRandomTooling());
        long count = Tooling.countToolings();
        Assert.assertTrue("Counter for 'Tooling' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ToolingIntegrationTest.testFindTooling() {
        Tooling obj = dod.getRandomTooling();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to provide an identifier", id);
        obj = Tooling.findTooling(id);
        Assert.assertNotNull("Find method for 'Tooling' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tooling' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ToolingIntegrationTest.testFindAllToolings() {
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", dod.getRandomTooling());
        long count = Tooling.countToolings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tooling', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tooling> result = Tooling.findAllToolings();
        Assert.assertNotNull("Find all method for 'Tooling' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tooling' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ToolingIntegrationTest.testFindToolingEntries() {
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", dod.getRandomTooling());
        long count = Tooling.countToolings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tooling> result = Tooling.findToolingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tooling' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tooling' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ToolingIntegrationTest.testFlush() {
        Tooling obj = dod.getRandomTooling();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to provide an identifier", id);
        obj = Tooling.findTooling(id);
        Assert.assertNotNull("Find method for 'Tooling' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTooling(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tooling' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolingIntegrationTest.testMergeUpdate() {
        Tooling obj = dod.getRandomTooling();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to provide an identifier", id);
        obj = Tooling.findTooling(id);
        boolean modified =  dod.modifyTooling(obj);
        Integer currentVersion = obj.getVersion();
        Tooling merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tooling' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", dod.getRandomTooling());
        Tooling obj = dod.getNewTransientTooling(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tooling' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tooling' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Tooling' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ToolingIntegrationTest.testRemove() {
        Tooling obj = dod.getRandomTooling();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tooling' failed to provide an identifier", id);
        obj = Tooling.findTooling(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tooling' with identifier '" + id + "'", Tooling.findTooling(id));
    }
    
}
