// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qa.domain;

import com.foamtec.qa.domain.TypeOfRequestIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TypeOfRequestIntegrationTest_Roo_Configurable {
    
    declare @type: TypeOfRequestIntegrationTest: @Configurable;
    
}
